package ai.routin.mytoken.feature.transfer

import java.time.Instant

/** Shared fixtures pinning the wire contract against real macOS CryptoKit output. */
object TransferFixtures {
    const val SESSION_ID = "5E7B0A62-9C1F-4E3A-8D2B-1F6C4A9E7D30"

    /** Generated by CryptoKit on macOS 26 (Swift 6.3); synthetic test key material only. */
    val MAC_PRIVATE_KEY: ByteArray = hex(
        "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f"
    )
    val ANDROID_PRIVATE_KEY: ByteArray = hex(
        "303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f"
    )
    val MAC_PUBLIC_KEY: ByteArray = hex(
        "d89e3bad79437dbed9f843418304f460ff05c7fe81fe4a9577a804cb9367ff66"
    )
    val ANDROID_PUBLIC_KEY: ByteArray = hex(
        "34e42d4af5ef94a07a3a84201b889d4cd1a743cb27b11b6a10438a8feb8e5847"
    )
    val SESSION_KEY: ByteArray = hex(
        "531ddc4fc1b0f928213d19d1486bead0bfd390281d307b6ab1db13f73678acac"
    )
    val NONCE: ByteArray = hex("000102030405060708090a0b")
    val TAG: ByteArray = hex("6e29d9b0be5577dd4bb34691cd12a06c")

    val CIPHERTEXT: ByteArray = hex(
        "2c77f05973cf7304227aee0b49fee7415625e66d6431b942fadab631da7eb60b06dcea7e0295b3debe478397bcd35349ff0513e40302828eb6e95c71015a842daabb8250907dd17b7a1e4371a52a2db3c734627ecefef5cde9acd295c4568cce0330670c0f360d20f902c3ba98b1c81d871a8fa5e2db7b471fa340c1cc493f72d40fdd75b4387307bd9002b79f562e19d3eb2da2828c26940920fb714ae091a3515bd04e7d7e0f721c8b0a3c3b6bee0537bf1ec521bceda3689871bb3fffe29b4c57b6a7119611d822394e327d14229062216407dee4e5370ad5bb5b211e6481e7f03e2194eeba824078a6057b74431227bba43a4e04dd3e45f4a820b9dd9132c059421ef4cac9fa55b11195dabe23b238a0d044f6fd8b1b00622ec4a6736f7b100a691f8ce96ea1625d93fe678041d2961e5483502c471bde2bb60df78f9d90c71a7a995fa4ac15dd25b8479bc8704f4ff4f0a8c054e39e90124886e99ba87e80892d288638bf116239f7b7bdf17d49e5f242d273938e934113da2255fd57bb1cde439c76a75dedded289a809e092b665138c9f88c61c14d84749f85265b157439facbe3eaaca4bc25a8a22014557d5d85d638f1ef22dad62a84dda7f7ddb552ba02f0e664b4020762844e953057e9271ec08cef5a048ab360489944336e1c92e0a3c2d40849c879d7f922a7636cd1b25c4a584a3ae274a82ee673e71de4615272dbfba433623a6083dca7b637de17d888b3c0fbf20939fc65690e42bc537758507f866773d4b8f36dd5a5155910392c0c794ee9afdf717d53a5f2eb0f060fa61d25d00cda64321ced0635aef5cd6ea1a4aa534e15ec3ebd8c1c20ba087a64ae55f7a274fb9df08694e2b5e9251c3abb64a8ea78f77a0e702d754f27611faf2aa6dd1fa328151679e39b94e94ed39bdc60ec208dd1317acb1941f18ceb262028660210d4af25a97c29c0ec98f7f2e8ba4aff8579ed1bcd9cdb1a3880c4f98674937750b37ba5bcafa8adc62c3"
    )

    const val PACKAGE_JSON =
        "{\"credentials\":[{\"credentialId\":\"A1B2C3D4-E5F6-4A7B-8C9D-0E1F2A3B4C5D\"," +
            "\"credentialKind\":\"bearerAPIKey\",\"isEnabled\":true,\"metadata\":{\"baseURL\":\"https://api.example.com/v1\"}," +
            "\"name\":\"Example Key\",\"providerId\":\"deepseek\",\"schemaVersion\":1,\"sortOrder\":0}]," +
            "\"exportedAt\":\"2026-09-07T03:00:00Z\",\"preferences\":{\"alertThresholds\":[50,80]," +
            "\"notificationsEnabled\":true,\"openAppRefresh\":true,\"pinnedCredentialIds\":[]," +
            "\"refreshIntervalMinutes\":15,\"wifiOnly\":false},\"schemaVersion\":1,\"secretEnvelope\":" +
            "{\"algorithm\":\"AES-256-GCM\",\"ciphertext\":\"AA\",\"entries\":[{\"bearerToken\":\"RXhhbXBsZVRva2Vu\"," +
            "\"credentialId\":\"A1B2C3D4-E5F6-4A7B-8C9D-0E1F2A3B4C5D\"}],\"ephemeralPublicKey\":\"AA\"," +
            "\"keyAgreement\":\"X25519-HKDF-SHA256\",\"nonce\":\"AA\",\"tag\":\"AA\"}}"

    /** Exact URI produced by `TransferQRCodePayload.encodedString()` on macOS. */
    const val QR_URI =
        "mytoken-transfer://v1?session=5E7B0A62-9C1F-4E3A-8D2B-1F6C4A9E7D30&host=192.168.1.10&port=52888" +
            "&publicKey=2J47rXlDfb7Z-ENBgwT0YP8Fx_6B_kqVd6gEy5Nn_2Y&expiry=2027-01-15T08:00:00.000Z&code=482913"

    const val EXPIRY_INSTANT = "2027-01-15T08:00:00.000Z"

    /** Fixed instant before the fixture expiry, for tests. */
    val NOW: Instant = Instant.parse("2026-09-07T03:00:00Z")

    fun hex(value: String): ByteArray =
        value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
